[workspace]
members = [
    "rustique-cli",
    "rustique-core",
]
resolver = "2"


[workspace.dependencies]
clap = { version = "4.6.6", features = ["color", "suggestions", "derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
dirs = { version = "6.0.0" }
serde_json5 = {  version = "0.2.1" }
chrono = { version =  "0.4.45" }
comfy-table = "8.0.0"
url = "2.5.8"
lenient_semver = "0.4.2"
semver = "1.0.28"
toml = { version = "1.1.4+spec-1.1.0", features = ["preserve_order"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
reqwest = { version = "0.13.4", features = ["json", "default-tls", "stream"], default-features = false }
tokio = { version = "1.53.1", features = ["fs","rt-multi-thread", "macros", "io-util"] }
clap_complete = "4.6.9"
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
indexmap = { version = "2.14.0", features = ["serde"] }
html2text = "0.17.1"
indicatif = { version = "0.18.6", features = ["tokio"] }
async_zip = { version = "0.0.18", features = ["tokio", "tokio-fs", "deflate"] }
futures = "0.3.33"
num_cpus = "1.17.0"
uuid = { version = "1.24.0", features = ["v4"] }
csv = "1.4.0"
is_elevated = "0.1.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
opt-level = 3
lto = "fat"
debug = false
codegen-units = 1
panic = "abort"
strip = "symbols"
